# Generated by Django 3.0.2 on 2020-03-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200310_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='noimage.jpg', upload_to='./pics'),
        ),
    ]
